# Generated by Django 4.1.4 on 2022-12-30 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import traitimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=traitimage.models.original_directory_path)),
                ('width', models.PositiveIntegerField(max_length=5)),
                ('height', models.PositiveIntegerField(max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('channels_number', models.PositiveBigIntegerField(max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SketchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=traitimage.models.sketch_directory_path)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('channels_number', models.PositiveBigIntegerField(max_length=1)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traitimage.originalimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
