# Generated by Django 4.1.4 on 2022-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traitimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalimage',
            name='channels_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='width',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sketchimage',
            name='channels_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
